### ISSUE TITLE
docker-compose failed

### ISSUE THREAD

**Issue by awni** [mzbac/mlx-chat-ui#1]
@mzbac I tried to get this to work but the command:

```
 docker-compose up --build
```

Failed with:

```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory
```

I didn't look into it yet, but thought I would post here in case you have seen it before.

**Comment by mzbac** [comment]
Yeah, it looks like there is Docker-related issue. Do you have Docker installed? It might be a bit tricky for you to install Docker Desktop, but there is an open-source alternative `Colima` that I have tested and it was working fine.

https://github.com/abiosoft/colima

**Comment by awni** [comment]
Yes I do have docker installed but maybe it is an old version or something...

**Comment by awni** [comment]
Edit: I have docker desktop installed, now it's working after I actually opened it.

**Comment by awni** [comment]
Now the docker is running but it's not letting me connect to localhost/chat

**Comment by mzbac** [comment]
> Now the docker is running but it's not letting me connect to localhost/chat

It defaults to HTTPS with a self-signed SSL certificate. You may need to allow the browser to visit the self-signed website.

**Comment by mzbac** [comment]
<img width="1253" alt="image" src="https://github.com/mzbac/mlx-chat-ui/assets/7523197/063de179-db6e-44fe-89b2-2d83332a9377">

**Comment by awni** [comment]
Hmm I'm not seeing that page..

<img width="687" alt="Screenshot 2024-02-12 at 7 57 02 PM" src="https://github.com/mzbac/mlx-chat-ui/assets/1542805/0c50dd18-fdd4-470d-bed8-03877866563a">

**Comment by mzbac** [comment]
Does `https://127.0.0.1/chat` work for you?

**Comment by awni** [comment]
No it's the same page :(

**Comment by mzbac** [comment]
> No it's the same page :(

Are you running the service on one machine and trying to access it from another machine? In that case, you have to start the mlx server with host 0.0.0.0.

**Comment by awni** [comment]
No I am running everything on the same laptop. It doesn't even look like localhost/chat is open though after starting the container. I do see some stuff in the log, can you discern anything?

```
chatui               | 03:59:44 1|index  | MongoServerSelectionError: connect ECONNREFUSED 192.168.65.2:27017
chatui               | 03:59:44 1|index  |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/sdam/topology.js:278:38)
chatui               | 03:59:44 1|index  |     at listOnTimeout (node:internal/timers:573:17)
chatui               | 03:59:44 1|index  |     at process.processTimers (node:internal/timers:514:7) {
chatui               | 03:59:44 1|index  |   reason: TopologyDescription {
chatui               | 03:59:44 1|index  |     type: 'Unknown',
chatui               | 03:59:44 1|index  |     servers: Map(1) { 'host.docker.internal:27017' => [ServerDescription] },
chatui               | 03:59:44 1|index  |     stale: false,
chatui               | 03:59:44 1|index  |     compatible: true,
chatui               | 03:59:44 1|index  |     heartbeatFrequencyMS: 10000,
chatui               | 03:59:44 1|index  |     localThresholdMS: 15,
chatui               | 03:59:44 1|index  |     setName: null,
chatui               | 03:59:44 1|index  |     maxElectionId: null,
chatui               | 03:59:44 1|index  |     maxSetVersion: null,
chatui               | 03:59:44 1|index  |     commonWireVersion: 0,
chatui               | 03:59:44 1|index  |     logicalSessionTimeoutMinutes: null
chatui               | 03:59:44 1|index  |   },
chatui               | 03:59:44 1|index  |   code: undefined,
chatui               | 03:59:44 1|index  |   [Symbol(errorLabels)]: Set(0) {}
chatui               | 03:59:44 1|index  | }
chatui               | 03:59:44 4|index  | MongoServerSelectionError: connect ECONNREFUSED 192.168.65.2:27017
chatui               | 03:59:44 4|index  |     at Timeout._onTimeout (/app/node_modules/mongodb/lib/sdam/topology.js:278:38)
chatui               | 03:59:44 4|index  |     at listOnTimeout (node:internal/timers:573:17)
chatui               | 03:59:44 4|index  |     at process.processTimers (node:internal/timers:514:7) {
chatui               | 03:59:44 4|index  |   reason: TopologyDescription {
chatui               | 03:59:44 4|index  |     type: 'Unknown',
chatui               | 03:59:44 4|index  |     servers: Map(1) { 'host.docker.internal:27017' => [ServerDescription] },
chatui               | 03:59:44 4|index  |     stale: false,
chatui               | 03:59:44 4|index  |     compatible: true,
chatui               | 03:59:44 4|index  |     heartbeatFrequencyMS: 10000,
chatui               | 03:59:44 4|index  |     localThresholdMS: 15,
chatui               | 03:59:44 4|index  |     setName: null,
chatui               | 03:59:44 4|index  |     maxElectionId: null,
chatui               | 03:59:44 4|index  |     maxSetVersion: null,
chatui               | 03:59:44 4|index  |     commonWireVersion: 0,
chatui               | 03:59:44 4|index  |     logicalSessionTimeoutMinutes: null
chatui               | 03:59:44 4|index  |   },
chatui               | 03:59:44 4|index  |   code: undefined,
chatui               | 03:59:44 4|index  |   [Symbol(errorLabels)]: Set(0) {}
chatui               | 03:59:44 4|index  | }
```

**Comment by awni** [comment]
The mlx lm server seems to be working fine but I can't figure out what's going on with the docker setup..

**Comment by mzbac** [comment]
looks like you local laptop has app used the mongo db default port..
use the command to check which app is using port 27017
```
sudo lsof -iTCP -sTCP:LISTEN -P -n

```
And temporarily kill that app.

**Comment by mzbac** [comment]
> The mlx lm server seems to be working fine but I can't figure out what's going on with the docker setup..

The Docker Compose failed to start MongoDB cause the chat-ui failed to start.

**Comment by awni** [comment]
Hmm don't see anything in the list using 27017..

**Comment by mzbac** [comment]
if you run `docker run -d -p 27017:27017 --name mongo-chatui mongo:latest` does it work on you local?

**Comment by mzbac** [comment]
try to updating the docker-compose.yml. Maybe your network configuration is somehow causing MongoDB to not be available on `192.168.65.2:27017`
```
version: '3'
services:
  nginx:
    build: 
     context: nginx
     dockerfile: Dockerfile
    network_mode: host
    depends_on:
     - chatui
  mongodb:
   image: mongo:latest
   container_name: mongodb
   network_mode: host
   command: ["mongod", "--bind_ip_all"]
  chatui:
   build: 
     context: ./chat-ui
     dockerfile: Dockerfile
   container_name: chatui
   depends_on:
     - mongodb
   network_mode: host
 ```

**Comment by awni** [comment]
> if you run docker run -d -p 27017:27017 --name mongo-chatui mongo:latest does it work on you local?

I see this in the browser:

```
It looks like you are trying to access MongoDB over HTTP on the native driver port.
```

**Comment by mzbac** [comment]
> > if you run docker run -d -p 27017:27017 --name mongo-chatui mongo:latest does it work on you local?
> 
> I see this in the browser:
> 
> ```
> It looks like you are trying to access MongoDB over HTTP on the native driver port.
> ```

Looks like there is no issue for MongoDB to run on your local machine. It seems like something to do with the network. Would you please kill all the docker containers by running `docker stop $(docker ps -q)` and try the docker-compose.yml shown above? See if letting MongoDB bind to all your available IP addresses would fix the issue.

**Comment by mzbac** [comment]
If the docker-compose doesn't work for you, you can try setting up instructions in chat-ui https://github.com/huggingface/chat-ui?tab=readme-ov-file#setup. You just need to change the .env.local file to point the API endpoint to your local mlx-lm server.

**Comment by awni** [comment]
Unfortunately I see the same issue with the updated config :(.

**Comment by awni** [comment]
I got it working using the chat-ui setup. Maybe you shoudl update the mlx-chat-ui docs to include a path for that? It could setup the `.env.local` file properly (I just had to change the MONGO DB url and the URL for the MLX LM server.

**Comment by mzbac** [comment]
> I got it working using the chat-ui setup. Maybe you shoudl update the mlx-chat-ui docs to include a path for that? It could setup the `.env.local` file properly (I just had to change the MONGO DB url and the URL for the MLX LM server.

Good point. I'm glad you got it working. I have updated the readme to include chat-ui's setup in case docker-compose doesn't work for some users.
